//
// build.gradle in TeamCode
//

apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    // Força a compatibilidade do Java 8 para casar com o build.common.gradle da SDK
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    mavenCentral()
    google()
    maven { url 'https://jitpack.io' }
    maven { url = 'https://maven.brott.dev/' }
}

dependencies {
    implementation project(':FtcRobotController')
}

// ----------------------------------------------------------------------------
// Tarefa Javadoc customizada
// ----------------------------------------------------------------------------
android.applicationVariants.all { variant ->
    task "generate${variant.name.capitalize()}Javadoc"(type: Javadoc) {
        group = "Documentation"
        description "Generates Javadoc for the ${variant.name} build."

        source = variant.javaCompile.source
        destinationDir = file("../docs")
        failOnError = false

        classpath = files(variant.javaCompile.classpath.files, project.android.getBootClasspath())

        options.links("http://docs.oracle.com/javase/8/docs/api/")
        options.links("https://javadoc.io/doc/org.firstinspires.ftc")
        exclude '**/R.java', '**/BuildConfig.java'
    }
}
